[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test/foundry'
cache_path = 'forge-cache'

[profile.ci]
fuzz_runs = 1000
verbosity = 4

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
