name: Test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - name: Run Hardhat tests
        run: npm run test:hardhat

      - name: Run Foundry tests
        run: npm run test:foundry
