name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Hardhat tests
        run: npm run test:hardhat
        
      - name: Run Foundry tests
        run: npm run test:foundry
